language: php
php:
  - 5.3
sudo: required
before_script:
  - /home/travis/.phpenv/versions/5.5/bin/composer install
  - ./tests/setup/before_script.sh
  - ./tests/setup/apache.sh
  - ./tests/setup/selenium.sh

script: phpunit tests/simpleTest.php
notifications:
  email:
    - soycaringal@gmail.com